# Generated by Django 5.0.1 on 2024-02-04 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCardSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('uniquec', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('service', 'Service'), ('sum', 'Sum')], default='sum', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('spent', 'Spent')], default='active', max_length=10)),
                ('spa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_gens_sum', to='website.spa')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('purchased_frequency', models.IntegerField()),
                ('uniquec', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('service', 'Service'), ('sum', 'Sum')], default='service', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('spent', 'Spent')], default='active', max_length=10)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.service')),
                ('spa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_gens_service', to='website.spa')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicCardSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('service', 'Service'), ('sum', 'Sum')], default='sum', max_length=10)),
                ('amount', models.IntegerField()),
                ('uniquec', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('spent', 'Spent')], default='active', max_length=10)),
                ('spa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elect_gens_sum', to='website.spa')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicCardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('service', 'Service'), ('sum', 'Sum')], default='service', max_length=10)),
                ('purchased_frequency', models.IntegerField()),
                ('uniquec', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('spent', 'Spent')], default='active', max_length=10)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elect_gens_service', to='website.service')),
                ('spa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elect_gens_service', to='website.spa')),
            ],
        ),
    ]
