# Generated by Django 5.0.1 on 2024-02-04 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_electroniccardservice_uniquec_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electroniccardservice',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='electroniccardsum',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='physicalcardservice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='physicalcardservice',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='physicalcardsum',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='electroniccardservice',
            name='uniquec',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electroniccardsum',
            name='uniquec',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalcardservice',
            name='uniquec',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalcardsum',
            name='uniquec',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electroniccardservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elect_gens_service', to='website.service'),
        ),
        migrations.AlterField(
            model_name='electroniccardservice',
            name='spa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elect_gens_service', to='website.spa'),
        ),
        migrations.AlterField(
            model_name='electroniccardservice',
            name='type',
            field=models.CharField(choices=[('service', 'Service'), ('sum', 'Sum')], default='service', max_length=10),
        ),
        migrations.AlterField(
            model_name='electroniccardsum',
            name='spa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elect_gens_sum', to='website.spa'),
        ),
        migrations.AlterField(
            model_name='electroniccardsum',
            name='type',
            field=models.CharField(choices=[('service', 'Service'), ('usual', 'Usual')], default='usual', max_length=10),
        ),
        migrations.AlterField(
            model_name='physicalcardservice',
            name='spa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_gens_service', to='website.spa'),
        ),
        migrations.AlterField(
            model_name='physicalcardservice',
            name='type',
            field=models.CharField(choices=[('service', 'Service'), ('sum', 'Sum')], default='service', max_length=10),
        ),
        migrations.AlterField(
            model_name='physicalcardsum',
            name='spa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_gens_sum', to='website.spa'),
        ),
        migrations.AlterField(
            model_name='physicalcardsum',
            name='type',
            field=models.CharField(choices=[('service', 'Service'), ('usual', 'Usual')], default='usual', max_length=10),
        ),
        migrations.AlterField(
            model_name='spa',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spa_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
