# Generated by Django 5.0.1 on 2024-01-17 15:02

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_papergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='papergen',
            name='unique',
            field=models.CharField(default=website.models.foo, max_length=30),
        ),
    ]
