# Generated by Django 5.0.1 on 2024-01-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_paper_electgen_alter_papergen_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electgen',
            old_name='unique',
            new_name='uniquec',
        ),
    ]
