# Generated by Django 5.0.1 on 2024-02-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_electroniccardservice_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalcardservice',
            old_name='purchased_frequency',
            new_name='amount',
        ),
    ]
